const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

// Infra per jaringan. WETH testnet = WETH9 canonical yang sudah ada di chain.
// v3Factory + positionManager TESTNET diisi dari output deploy-uniswap-infra.js
// (jalankan itu dulu sekali). MAINNET pakai deployment resmi Uniswap.
const NETWORKS = {
  robinhoodTestnet: {
    chainId: 46630,
    chainHex: "0xb626",
    rpcUrl: "https://rpc.testnet.chain.robinhood.com",
    explorerUrl: "https://explorer.testnet.chain.robinhood.com",
    weth: "0x33e4191705c386532ba27cBF171Db86919200B94",
    v3Factory: "0xBC7832D7B3A1D16922ddB0BeF501CCC9157CdDb7",
    positionManager: "0x11a81C212fb97AF8c89De811F3530Db15592faf2",
    swapRouter02: "0x05FaE28A5917DA56D464fcfC13Ee9141B4FC057c",
    quoterV2: "0xd9613Dd50dD035FB630181811dD65191791BeFB6",
  },
  robinhoodMainnet: {
    chainId: 4663,
    chainHex: "0x1237",
    rpcUrl: "https://rpc.mainnet.chain.robinhood.com",
    explorerUrl: "https://robinhoodchain.blockscout.com",
    weth: "0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73", // canonical Robinhood WETH
    v3Factory: "0x1f7d7550b1b028f7571e69a784071f0205fd2efa", // Uniswap resmi
    positionManager: "0x73991a25c818bf1f1128deaab1492d45638de0d3", // Uniswap resmi
    swapRouter02: "0xcaf681a66d020601342297493863e78c959e5cb2", // Uniswap resmi
    quoterV2: "0x33e885ed0ec9bf04ecfb19341582aadcb4c8a9e7", // Uniswap resmi
  },
};

async function main() {
  const netName = hre.network.name;
  const net = NETWORKS[netName];
  if (!net) throw new Error(`Network ${netName} tidak dikenal di scripts/deploy.js`);
  if (String(net.v3Factory).startsWith("FILL") || String(net.weth).startsWith("FILL")) {
    throw new Error(
      `Alamat infra untuk ${netName} belum diisi. Jalankan "npm run deploy:infra:testnet" dulu, lalu tempel hasilnya ke NETWORKS di scripts/deploy.js.`
    );
  }

  const [deployer] = await hre.ethers.getSigners();
  const expectedDeployer = process.env.EXPECTED_DEPLOYER;
  if (
    expectedDeployer &&
    deployer.address.toLowerCase() !== expectedDeployer.toLowerCase()
  ) {
    throw new Error(`Deployer mismatch: expected ${expectedDeployer}, got ${deployer.address}`);
  }
  const treasury = process.env.PROTOCOL_TREASURY || deployer.address;
  const creatorVestingWallet =
    process.env.CREATOR_VESTING_WALLET || deployer.address;
  if (netName === "robinhoodMainnet" && (!process.env.PROTOCOL_TREASURY || !process.env.CREATOR_VESTING_WALLET)) {
    throw new Error("Mainnet requires explicit PROTOCOL_TREASURY and CREATOR_VESTING_WALLET");
  }
  console.log("Network:", netName, `(chainId ${net.chainId})`);
  console.log("Deployer:", deployer.address);
  console.log("Protocol treasury:", treasury);
  console.log("Creator vesting wallet (ordinary wallet):", creatorVestingWallet);

  const balance = await hre.ethers.provider.getBalance(deployer.address);
  console.log("Gas balance (ETH):", hre.ethers.formatEther(balance));

  const args = [
    net.weth,
    net.v3Factory,
    net.positionManager,
    treasury,
    creatorVestingWallet,
    deployer.address,
  ];
  const pad = await hre.ethers.deployContract("HoodLaunchpad", args);
  await pad.waitForDeployment();
  const addr = await pad.getAddress();
  console.log("HoodLaunchpad:", addr);
  console.log("Explorer:", `${net.explorerUrl}/address/${addr}`);

  const routerArgs = [net.weth, addr, net.v3Factory, treasury];
  const router = await hre.ethers.deployContract("HoodSwapRouter", routerArgs);
  await router.waitForDeployment();
  const routerAddr = await router.getAddress();
  console.log("HoodSwapRouter:", routerAddr);
  console.log("Router explorer:", `${net.explorerUrl}/address/${routerAddr}`);

  // Tulis config frontend (dibaca index.html bagian Token Agent + Market).
  const deploymentFile = path.resolve(__dirname, "../../hood-deployment.js");
  fs.writeFileSync(
    deploymentFile,
    `/* Generated by contracts/scripts/deploy.js — do not edit by hand */\n` +
      `window.HOOD_DEPLOYMENT = Object.freeze({\n` +
      `  launchpad: "${addr}",\n` +
      `  swapRouter: "${routerAddr}",\n` +
      `  network: "${netName}",\n` +
      `  chainId: ${net.chainId},\n` +
      `  chainHex: "${net.chainHex}",\n` +
      `  chainName: "${netName === "robinhoodMainnet" ? "Robinhood Chain" : "Robinhood Chain Testnet"}",\n` +
      `  rpcUrl: "${net.rpcUrl}",\n` +
      `  explorerUrl: "${net.explorerUrl}",\n` +
      `  weth: "${net.weth}",\n` +
      `  swapRouter02: "${net.swapRouter02}",\n` +
      `  quoterV2: "${net.quoterV2}",\n` +
      `  dexName: "Uniswap V3",\n` +
      `});\n`
  );
  console.log("Frontend deployment config updated:", deploymentFile);

  // Selalu langsung verify (aturan rumah).
  console.log("Verifying on Blockscout...");
  try {
    await hre.run("verify:verify", { address: addr, constructorArguments: args });
    await hre.run("verify:verify", {
      address: routerAddr,
      constructorArguments: routerArgs,
    });
    console.log("Launchpad dan router verified.");
  } catch (err) {
    console.error("Verifikasi gagal, ulangi manual dengan:");
    console.error(
      `npx hardhat verify --network ${netName} ${addr} ${args.join(" ")}`
    );
    console.error(String(err.message || err));
  }
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
